'use client';

import { useState } from 'react';

const FAQS = [
  {
    q: 'Can I customise my meal plan?',
    a: 'Yes. Set your dietary needs, calorie and protein targets, budget, and cook time, and swap out any meal you don’t like without touching the rest of your week.',
  },
  {
    q: 'Is there a free version?',
    a: 'Yes. Free gives you 5 personalised weekly meal plans every month, access to 24 free recipes, and a full grocery list with every plan — no credit card required. Premium (€7.77/month) removes the monthly limit and unlocks all 235 recipes, so you can generate and regenerate as often as you like.',
  },
  {
    q: 'Can I regenerate meals?',
    a: 'Yes — generate a new plan anytime, or regenerate just one day if only part of the week needs changing.',
  },
  {
    q: 'How does the AI work?',
    a: 'You set your goals, and the AI builds a full week of recipes from our real recipe library, scaled and combined to match your calorie and protein targets. Nutrition numbers are calculated directly from each recipe’s ingredients rather than generated by AI.',
  },
  {
    q: 'Can vegetarians use it?',
    a: 'Yes. Set your dietary needs to vegetarian, vegan, dairy-free, or gluten-free and every plan respects it.',
  },
  {
    q: 'Can I build muscle with this?',
    a: 'Yes. Set your goal to “build muscle” and your protein target is calculated and built into every meal.',
  },
  {
    q: 'Can I lose weight with this?',
    a: 'Yes. Set your goal to “lose weight” and your calorie target is calculated from your stats using the Mifflin-St Jeor formula.',
  },
];

const FAQ_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQS.map((item) => ({
    '@type': 'Question',
    name: item.q,
    acceptedAnswer: { '@type': 'Answer', text: item.a },
  })),
};

export default function FAQ() {
  const [open, setOpen] = useState(null);

  return (
    <section className="px-6 py-16">
      <div className="mx-auto max-w-[760px]">
        <h2 className="mb-2 text-center text-2xl font-extrabold text-green-900">Frequently asked questions</h2>
        <p className="mb-8 text-center text-sm text-ink-soft">Everything you need to know.</p>
        <div className="divide-y divide-gray-200 overflow-hidden rounded-2xl border border-gray-200 bg-white">
          {FAQS.map((item, i) => {
            const isOpen = open === i;
            const panelId = `faq-panel-${i}`;
            const buttonId = `faq-button-${i}`;
            return (
              <div key={item.q}>
                <h3 className="m-0">
                  <button
                    id={buttonId}
                    type="button"
                    aria-expanded={isOpen}
                    aria-controls={panelId}
                    onClick={() => setOpen(isOpen ? null : i)}
                    className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left text-sm font-bold text-ink transition-colors duration-200 hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-green-600"
                  >
                    {item.q}
                    <span
                      aria-hidden="true"
                      className={`shrink-0 text-lg transition-colors duration-200 ${isOpen ? 'text-green-600' : 'text-gray-400'}`}
                    >
                      {isOpen ? '−' : '+'}
                    </span>
                  </button>
                </h3>
                <div
                  id={panelId}
                  role="region"
                  aria-labelledby={buttonId}
                  className="overflow-hidden transition-[max-height] duration-300 ease-in-out"
                  style={{ maxHeight: isOpen ? '400px' : '0px' }}
                >
                  <div className="px-5 pb-4 text-sm text-ink-soft">{item.a}</div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(FAQ_SCHEMA) }}
      />
    </section>
  );
}
