const POINTS = [
  { icon: '📚', text: '235 macro-tracked recipes' },
  { icon: '🛒', text: 'Grocery lists generated automatically' },
  { icon: '⏱️', text: 'Weekly meal plans created in under a minute' },
  { icon: '🧮', text: 'Nutrition calculated from real recipe ingredients' },
  { icon: '⚖️', text: 'Serving sizes automatically adjusted' },
  { icon: '🥗', text: 'Diet preferences applied to every generated plan' },
  { icon: '✅', text: 'Cancel Premium anytime, no cancellation fees' },
];

export default function TrustSection() {
  return (
    <section className="bg-green-50 px-6 py-16">
      <div className="mx-auto max-w-[1120px]">
        <h2 className="text-center text-2xl font-extrabold text-green-900">Built around real recipe data</h2>
        <p className="mx-auto mb-10 mt-2 max-w-xl text-center text-ink-soft">
          Every number you see comes from the recipe itself — not a guess.
        </p>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-2 md:grid-cols-4">
          {POINTS.map((p) => (
            <div
              key={p.text}
              className="flex flex-col items-center gap-2 rounded-2xl border border-green-100 bg-white p-5 text-center"
            >
              <span className="text-2xl">{p.icon}</span>
              <span className="text-sm font-semibold text-ink">{p.text}</span>
            </div>
          ))}
        </div>
        <p className="mx-auto mt-8 max-w-lg text-center text-xs text-ink-soft">
          🔍 Calculated from each recipe's ingredients and serving size, not generated by AI. Actual values can
          vary slightly by ingredient brand and preparation.
        </p>
      </div>
    </section>
  );
}
