const POINTS = [
  { icon: '📚', text: '235 structured recipes' },
  { icon: '🧮', text: 'Calories calculated from real ingredients' },
  { icon: '🥩', text: 'Accurate macro calculations' },
  { icon: '🛒', text: 'Automatic shopping list generation' },
  { icon: '🔗', text: 'Ingredient quantities consolidated across the entire week' },
  { icon: '⚖️', text: 'Serving sizes automatically adjusted' },
  { icon: '🥗', text: 'Diet preferences applied to every generated plan' },
];

export default function TrustSection() {
  return (
    <section className="bg-green-50 px-6 py-16">
      <div className="mx-auto max-w-[1120px]">
        <h2 className="text-center text-2xl font-extrabold text-green-900">Built around real recipe data</h2>
        <p className="mx-auto mb-10 mt-2 max-w-xl text-center text-ink-soft">
          Every number you see comes from the recipe itself — not a guess.
        </p>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-2 md:grid-cols-4">
          {POINTS.map((p) => (
            <div
              key={p.text}
              className="flex flex-col items-center gap-2 rounded-2xl border border-green-100 bg-white p-5 text-center"
            >
              <span className="text-2xl">{p.icon}</span>
              <span className="text-sm font-semibold text-ink">{p.text}</span>
            </div>
          ))}
        </div>
        <p className="mx-auto mt-8 max-w-lg text-center text-xs text-ink-soft">
          🔍 Nutritional values are calculated directly from the ingredients and serving sizes in our recipe
          database rather than generated by AI. Actual values may vary depending on ingredient brands and
          preparation methods.
        </p>
      </div>
    </section>
  );
}
